include: arc_common_yaml
task: arc_easy_nya
dataset_name: nya
dataset_kwargs:
  data_files:
    validation: data/nya/eval/ai2_arc_easy_validation_english2nya_microsoft_translated.jsonl
    test: data/nya/eval/ai2_arc_easy_test_english2nya_microsoft_translated.jsonl
doc_to_text: "Funso: {{question}}\nYankho:"
