include: xstorycloze_common_yaml
task: xstorycloze_nya
dataset_name: nya
dataset_kwargs:
  data_files:
    train: data/nya/eval/xstory_cloze_train_english2nya_microsoft_translated.jsonl
    eval:  data/nya/eval/xstory_cloze_eval_english2nya_microsoft_translated.jsonl
